export const DEFAULT_CATEGORY_KEYS = {
  expense: [
    'food', 'grocery', 'transport', 'shopping', 'utility_bills', 
    'mobile_recharge', 'internet', 'rent', 'medical', 'education', 
    'family', 'entertainment', 'fuel', 'maintenance', 'savings_dps', 
    'travel', 'donation', 'business_exp', 'loan_repayment', 'other'
  ],
  income: [
    'salary', 'bonus', 'freelancing', 'business_profit', 
    'investment', 'gift', 'rent_income', 'sales', 'other'
  ]
};

export const PAYMENT_METHOD_KEYS = [
  'cash', 'bkash', 'nagad_mfs', 'bank', 'other'
];

export const TRANSLATIONS: Record<string, any> = {
  bn: {
    appName: 'টাকা ট্র্যাকার',
    dashboard: 'ড্যাশবোর্ড',
    transactions: 'হিসাব',
    budgets: 'বাজেট',
    settings: 'সেটিংস',
    totalIncome: 'মোট আয়',
    totalExpense: 'মোট ব্যয়',
    currentBalance: 'ব্যালেন্স',
    addTransaction: 'আয় ও ব্যয় যুক্ত করুন',
    transactionList: 'সাম্প্রতিক লেনদেন',
    amount: 'পরিমাণ',
    date: 'তারিখ',
    category: 'ক্যাটাগরি',
    paymentMethod: 'লেনদেনের মাধ্যম',
    note: 'নোট (ঐচ্ছিক)',
    income: 'আয়',
    expense: 'ব্যয়',
    save: 'সংরক্ষণ করুন',
    confirmSave: 'নিশ্চিত করুন',
    cancel: 'বাতিল করুন',
    delete: 'মুছে ফেলুন',
    confirmDeleteBtn: 'হ্যাঁ, মুছে ফেলুন',
    edit: 'পরিবর্তন করুন',
    setBudget: 'বাজেট পরিবর্তন',
    addBudgetBtn: '+ বাজেট যোগ করুন',
    limit: 'সীমা',
    backupData: 'ব্যাকআপ নিন',
    restoreData: 'রিস্টোর করুন',
    budgetEntryTitle: 'বাজেট ক্যাটাগরি',
    entryEntryTitle: 'আয় ও ব্যয় এন্ট্রি',
    confirmDeleteBudget: 'আপনি কি নিশ্চিত এই বাজেট ক্যাটাগরি মুছে ফেলতে চান?',
    confirmDeleteEntry: 'এই এন্ট্রিটি মুছে ফেলতে চান?',
    budgetDeleteSuccess: 'বাজেট মুছে ফেলা হয়েছে',
    entryDeleteSuccess: 'এন্ট্রি মুছে ফেলা হয়েছে',
    saveSuccess: 'সংরক্ষণ সফল হয়েছে',
    logout: 'লগআউট',
    filter: 'ফিল্টার',
    clearFilters: 'সব মুছুন',
    allCategories: 'সব ক্যাটাগরি',
    startDate: 'শুরু তারিখ',
    endDate: 'শেষ তারিখ',
    generalSettings: 'সাধারণ সেটিংস',
    dataSecurity: 'ডাটা ও সিকিউরিটি',
    notifSection: 'নোটিফিকেশন',
    reportSection: 'রিপোর্ট ও এক্সপোর্ট',
    darkMode: 'ডার্ক মোড',
    language: 'ভাষা (Language)',
    appLock: 'অ্যাপ লক (পিন)',
    updatePin: 'পিন পরিবর্তন',
    budgetAlert: 'বাজেট সতর্কবার্তা',
    dailyReminder: 'দৈনিক রিমাইন্ডার',
    privacyPolicy: 'প্রাইভেসি পলিসি',
    selectMonth: 'মাস নির্বাচন করুন',
    exportCSV: 'এক্সপোর্ট (CSV)',
    setupPin: 'পিন সেট করুন',
    lockApp: 'সুরক্ষিত করুন',
    enterPin: 'পিন দিন',
    pinMismatch: 'পিন মেলেনি!',
    pinSuccess: 'পিন সফলভাবে আপডেট হয়েছে',
    stepOldPin: 'পুরানো পিন দিন',
    stepNewPin: 'নতুন পিন দিন',
    stepConfirmPin: 'পুনরায় পিন দিন',
    oldPinWrong: 'পুরানো পিন ভুল',
    next: 'পরবর্তী',
    fromDate: 'শুরু তারিখ',
    toDate: 'শেষ তারিখ',
    daily: 'আজকের',
    monthly: 'এই মাসের',
    yearly: 'এই বছরের',
    categories: {
      food: 'খাবার ও রেস্টুরেন্ট', grocery: 'বাজার', transport: 'যাতায়াত', 
      shopping: 'কেনাকাটা', utility_bills: 'বিল', 
      mobile_recharge: 'রিচার্জ', internet: 'ইন্টারনেট', 
      rent: 'ভাড়া', medical: 'চিকিৎসা', education: 'শিক্ষা', 
      family: 'পরিবার', entertainment: 'বিনোদন', fuel: 'জ্বালানি', 
      maintenance: 'মেরামত', savings_dps: 'সঞ্চয়', travel: 'ভ্রমণ', 
      donation: 'দান', business_exp: 'ব্যবসা', 
      loan_repayment: 'ঋণ', salary: 'বেতন', bonus: 'বোনাস', 
      freelancing: 'ফ্রিল্যান্সিং', business_profit: 'মুনাফা', 
      investment: 'বিনিয়োগ', gift: 'উপহার', 
      rent_income: 'ভাড়া প্রাপ্তি', sales: 'বিক্রি', other: 'অন্যান্য'
    },
    payments: {
      cash: 'নগদ', bkash: 'বিকাশ', nagad_mfs: 'নগদ (MFS)', bank: 'ব্যাংক', other: 'অন্যান্য'
    }
  },
  en: {
    appName: 'Taka Tracker',
    dashboard: 'Dashboard',
    transactions: 'History',
    budgets: 'Budgets',
    settings: 'Settings',
    totalIncome: 'Income',
    totalExpense: 'Expense',
    currentBalance: 'Balance',
    addTransaction: 'Add Income & Expense',
    transactionList: 'Recent Records',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    paymentMethod: 'Payment Method',
    note: 'Note',
    income: 'Income',
    expense: 'Expense',
    save: 'Save',
    confirmSave: 'Confirm',
    cancel: 'Cancel',
    delete: 'Delete',
    confirmDeleteBtn: 'Yes, Delete',
    edit: 'Edit',
    setBudget: 'Edit Budget',
    addBudgetBtn: '+ Add Budget',
    limit: 'Limit',
    backupData: 'Backup',
    restoreData: 'Restore',
    budgetEntryTitle: 'Budget Categories',
    entryEntryTitle: 'Entry Records',
    confirmDeleteBudget: 'Are you sure you want to delete this budget category?',
    confirmDeleteEntry: 'Delete this entry?',
    budgetDeleteSuccess: 'Budget deleted',
    entryDeleteSuccess: 'Entry deleted',
    saveSuccess: 'Saved successfully',
    logout: 'Logout',
    filter: 'Filter',
    clearFilters: 'Clear All',
    allCategories: 'All Categories',
    startDate: 'Start Date',
    endDate: 'End Date',
    generalSettings: 'General Settings',
    dataSecurity: 'Data & Security',
    notifSection: 'Notifications',
    reportSection: 'Report & Export',
    darkMode: 'Dark Mode',
    language: 'Language',
    appLock: 'App Lock (PIN)',
    updatePin: 'Change PIN',
    budgetAlert: 'Budget Warning',
    dailyReminder: 'Daily Reminder',
    privacyPolicy: 'Privacy Policy',
    selectMonth: 'Select Month',
    exportCSV: 'Export (CSV)',
    setupPin: 'Setup PIN',
    lockApp: 'Lock App',
    enterPin: 'Enter PIN',
    pinMismatch: 'PIN Mismatch!',
    pinSuccess: 'PIN updated successfully',
    stepOldPin: 'Old PIN',
    stepNewPin: 'New PIN',
    stepConfirmPin: 'Confirm PIN',
    oldPinWrong: 'Incorrect old PIN',
    next: 'Next',
    fromDate: 'From',
    toDate: 'To',
    daily: 'Today',
    monthly: 'Monthly',
    yearly: 'Yearly',
    categories: {
      food: 'Food & Restaurant', grocery: 'Grocery', transport: 'Transport', 
      shopping: 'Shopping', utility_bills: 'Bills', 
      mobile_recharge: 'Recharge', internet: 'Internet', 
      rent: 'Rent', medical: 'Medical', education: 'Education', 
      family: 'Family', entertainment: 'Entertainment', fuel: 'Fuel', 
      maintenance: 'Maintenance', savings_dps: 'Savings', travel: 'Travel', 
      donation: 'Donation', business_exp: 'Business', 
      loan_repayment: 'Loan', salary: 'Salary', bonus: 'Bonus', 
      freelancing: 'Freelancing', business_profit: 'Profit', 
      investment: 'Investment', gift: 'Gift', 
      rent_income: 'Rent Income', sales: 'Sales', other: 'Other'
    },
    payments: {
      cash: 'Cash', bkash: 'bKash', nagad_mfs: 'Nagad (MFS)', bank: 'Bank', other: 'Other'
    }
  }
};